import Link from "next/link";

const sectionStyle = { marginBottom: 24 };
const h2Style = { fontFamily: "var(--font-cormorant)", fontSize: "18px", fontWeight: 600, color: "var(--ink)", marginBottom: 8 };
const pStyle = { fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 12 };
const pStyleLast = { fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 0 };
const ulStyle = { fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 12, paddingLeft: 20 };

export default function TermsPage() {
  return (
    <main style={{ minHeight: "100vh", background: "var(--bg)", padding: "48px 24px" }}>
      <div style={{ maxWidth: 560, margin: "0 auto" }}>
        <Link href="/" style={{ fontSize: "12px", color: "var(--ink-soft)", textDecoration: "none", marginBottom: 32, display: "inline-block" }}>
          ← Back to GoShed
        </Link>
        <h1 style={{ fontFamily: "var(--font-cormorant)", fontSize: "28px", fontWeight: 600, color: "var(--ink)", marginBottom: 4 }}>
          GoShed Terms of Service
        </h1>
        <p style={{ fontSize: "13px", color: "var(--ink-soft)", marginBottom: 32 }}>Last Updated: March 2026</p>

        <section style={sectionStyle}>
          <p style={pStyle}>
            Welcome to GoShed, a service provided by ThriftShopper Inc. (&ldquo;GoShed,&rdquo; &ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;). These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of the GoShed mobile application, website, and any related services (collectively, the &ldquo;Service&rdquo;). By accessing or using the Service, you agree to be bound by these Terms.
          </p>
          <p style={pStyleLast}>If you do not agree to these Terms, do not use GoShed.</p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>1. Purpose of GoShed</h2>
          <p style={pStyle}>
            GoShed provides tools that generate recommendations, reminders, and suggestions to help users make decisions about purchases, gifts, events, and other everyday choices.
          </p>
          <p style={pStyleLast}>
            GoShed is a decision‑support tool only. It is not a substitute for your own judgment, professional advice, or independent research.
          </p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>2. Eligibility and Accounts</h2>
          <p style={pStyle}>You must be at least 13 years old, or the minimum age of digital consent in your jurisdiction, to use GoShed.</p>
          <p style={pStyle}>You are responsible for maintaining the confidentiality of your account and for all activity that occurs under your account.</p>
          <p style={pStyle}>You agree to provide accurate information and to update it as needed to keep it current.</p>
          <p style={pStyleLast}>We may suspend or terminate your access to the Service if we reasonably believe you have violated these Terms or used the Service in a harmful or unlawful way.</p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>3. Recommendations and AI‑Generated Content</h2>
          <p style={pStyle}>GoShed may provide suggestions, rankings, or recommendations generated by automated systems and AI models.</p>
          <p style={pStyle}>These recommendations:</p>
          <ul style={ulStyle}>
            <li>Are informational only.</li>
            <li>Are not guarantees, endorsements, or professional advice.</li>
            <li>May be incomplete, inaccurate, outdated, or inappropriate for your particular situation.</li>
          </ul>
          <p style={pStyleLast}>You are solely responsible for any decisions or actions you take based on GoShed&apos;s recommendations. GoShed does not provide financial, legal, medical, or other professional advice.</p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>4. Your Responsibilities</h2>
          <p style={pStyle}>By using GoShed, you agree that you will:</p>
          <ul style={ulStyle}>
            <li>Use the Service only for lawful purposes and in compliance with these Terms.</li>
            <li>Not misuse, interfere with, or attempt to disrupt the Service or its infrastructure.</li>
            <li>Not reverse engineer, decompile, or attempt to access the underlying source code or systems, except where allowed by applicable law.</li>
            <li>Not submit content that is illegal, infringing, abusive, or otherwise violates the rights of others.</li>
          </ul>
          <p style={pStyleLast}>You remain responsible for your content and for any consequences of sharing or acting on information within GoShed.</p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>5. Third‑Party Products, Services, and Links</h2>
          <p style={pStyle}>GoShed may reference or surface products, services, businesses, or third‑party content (including via recommendations or links).</p>
          <ul style={ulStyle}>
            <li>These references and suggestions are not endorsements or guarantees.</li>
            <li>GoShed is not a party to any transactions you make with third parties.</li>
            <li>We are not responsible for third‑party products, services, content, websites, or your experiences with them.</li>
            <li>You should review the terms and privacy policies of any third‑party sites or services you choose to use.</li>
          </ul>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>6. Ownership and License</h2>
          <p style={pStyle}>The Service, including its content, features, and underlying technology, is owned by ThriftShopper Inc. and its licensors and is protected by intellectual property laws.</p>
          <p style={pStyle}>Subject to your compliance with these Terms, we grant you a limited, non‑exclusive, non‑transferable, revocable license to use the GoShed app and Service for your personal, non‑commercial use.</p>
          <p style={pStyle}>You may not:</p>
          <ul style={ulStyle}>
            <li>Copy, modify, distribute, sell, lease, or create derivative works based on the Service.</li>
            <li>Use any automated means (such as bots or scrapers) to access the Service, except as expressly permitted by us.</li>
          </ul>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>7. Service Changes and Availability</h2>
          <p style={pStyle}>We are continuously improving GoShed and may:</p>
          <ul style={ulStyle}>
            <li>Add, modify, or remove features or functionality.</li>
            <li>Update the app or underlying systems.</li>
            <li>Suspend or discontinue all or part of the Service.</li>
          </ul>
          <p style={pStyleLast}>We do not guarantee that the Service will be available at all times or free from errors, interruptions, or delays.</p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>8. Disclaimers</h2>
          <p style={pStyle}>The Service is provided on an &ldquo;AS IS&rdquo; and &ldquo;AS AVAILABLE&rdquo; basis, without warranties of any kind, whether express or implied.</p>
          <p style={pStyle}>To the fullest extent permitted by law, we disclaim all warranties, including but not limited to:</p>
          <ul style={ulStyle}>
            <li>Warranties of merchantability, fitness for a particular purpose, and non‑infringement.</li>
            <li>Any warranty that the Service will be uninterrupted, secure, timely, or error‑free.</li>
            <li>Any warranty regarding the accuracy, reliability, or completeness of any recommendations or content.</li>
          </ul>
          <p style={pStyleLast}>You use the Service at your own risk.</p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>9. Limitation of Liability</h2>
          <p style={pStyle}>To the fullest extent permitted by law, GoShed, ThriftShopper Inc., and their officers, directors, employees, and agents will not be liable for any:</p>
          <ul style={ulStyle}>
            <li>Decisions or actions you take based on recommendations, suggestions, or content from the Service.</li>
            <li>Purchases, financial outcomes, or other consequences of your decisions.</li>
            <li>Loss of data, loss of profits, business interruption, or any indirect, incidental, special, consequential, or punitive damages.</li>
          </ul>
          <p style={pStyle}>Our total liability for any claims arising out of or relating to the Service or these Terms will not exceed the greater of: (a) the amount you paid to us for the Service in the six (6) months preceding the claim, or (b) ten U.S. dollars (USD $10).</p>
          <p style={pStyleLast}>Some jurisdictions do not allow the exclusion or limitation of certain damages or warranties, so some of the above limitations may not apply to you.</p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>10. Indemnification</h2>
          <p style={pStyle}>You agree to indemnify, defend, and hold harmless GoShed, ThriftShopper Inc., and their officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable attorneys&apos; fees) arising out of or related to:</p>
          <ul style={ulStyle}>
            <li>Your use of the Service.</li>
            <li>Your content or interactions within the Service.</li>
            <li>Your violation of these Terms or any applicable law.</li>
          </ul>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>11. Termination</h2>
          <p style={pStyle}>We may suspend or terminate your access to the Service at any time, with or without notice, if we reasonably believe: you have violated these Terms, or your use may cause harm to us, the Service, or other users.</p>
          <p style={pStyleLast}>You may stop using the Service at any time and may delete your account where available. Sections that by their nature should survive termination (such as ownership, disclaimers, limitation of liability, and indemnification) will continue to apply.</p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>12. Governing Law</h2>
          <p style={pStyle}>These Terms are governed by and construed in accordance with the laws of the State of New York, without regard to its conflict of laws principles, unless a different law is required by the laws of your jurisdiction.</p>
          <p style={pStyleLast}>Any disputes arising out of or relating to these Terms or the Service will be subject to the exclusive jurisdiction of the state and federal courts located in New York, New York, unless applicable law requires otherwise.</p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>13. Changes to These Terms</h2>
          <p style={pStyle}>We may update these Terms from time to time. When we do, we will revise the &ldquo;Last Updated&rdquo; date at the top of this page. If we make material changes, we may provide additional notice, such as an in‑app notification or email.</p>
          <p style={pStyleLast}>Your continued use of the Service after the updated Terms become effective constitutes your acceptance of the changes. If you do not agree to the updated Terms, you must stop using GoShed.</p>
        </section>

        <section style={sectionStyle}>
          <h2 style={h2Style}>14. Subscriptions and Auto-Renewal</h2>
          <p style={pStyle}>GoShed may offer paid auto-renewing subscriptions, such as monthly or yearly GoShed Pro access, through Apple in-app purchase on iOS.</p>
          <ul style={ulStyle}>
            <li>Payment is charged to your Apple ID at confirmation of purchase.</li>
            <li>Subscriptions renew automatically unless canceled at least 24 hours before the end of the current billing period.</li>
            <li>Your account may be charged for renewal within 24 hours before the end of the current period.</li>
            <li>You can manage or cancel your subscription in your App Store account settings after purchase.</li>
            <li>If you cancel, you keep access to paid features until the end of the current billing period.</li>
            <li>Refund requests and billing issues for Apple purchases are handled by Apple under its App Store policies.</li>
          </ul>
          <p style={pStyleLast}>Subscription prices and billing periods are shown in the app before purchase and may vary by region or App Store settings.</p>
        </section>

        <section style={{ marginBottom: 0 }}>
          <h2 style={h2Style}>15. Contact</h2>
          <p style={pStyle}>If you have questions about these Terms or the Service, please contact us at:</p>
          <p style={pStyle}>ThriftShopper Inc. / GoShed</p>
          <p style={pStyleLast}>Email: <span style={{ color: "var(--accent)" }}>support@thriftshopper.com</span></p>
        </section>
      </div>
    </main>
  );
}
