import Link from "next/link";

export default function TermsPage() {
  return (
    <main style={{ minHeight: "100vh", background: "var(--bg)", padding: "48px 24px" }}>
      <div style={{ maxWidth: 560, margin: "0 auto" }}>
        <Link href="/" style={{ fontSize: "12px", color: "var(--ink-soft)", textDecoration: "none", marginBottom: 32, display: "inline-block" }}>
          ← Back to GoShed
        </Link>
        <h1 style={{ fontFamily: "var(--font-cormorant)", fontSize: "28px", fontWeight: 600, color: "var(--ink)", marginBottom: 4 }}>
          GoShed Terms of Service
        </h1>
        <p style={{ fontSize: "13px", color: "var(--ink-soft)", marginBottom: 32 }}>Last Updated: March 2026</p>

        <section style={{ marginBottom: 24 }}>
          <p style={{ fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 0 }}>
            Welcome to GoShed. By accessing or using the GoShed website or services, you agree to the following terms.
          </p>
        </section>

        <section style={{ marginBottom: 24 }}>
          <h2 style={{ fontFamily: "var(--font-cormorant)", fontSize: "18px", fontWeight: 600, color: "var(--ink)", marginBottom: 8 }}>1. Purpose of GoShed</h2>
          <p style={{ fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 8 }}>
            GoShed provides tools that generate recommendations, reminders, and suggestions to help users make decisions about purchases, gifts, events, and other everyday choices.
          </p>
          <p style={{ fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 0 }}>
            GoShed is intended as a decision support tool, not a substitute for personal judgment.
          </p>
        </section>

        <section style={{ marginBottom: 24 }}>
          <h2 style={{ fontFamily: "var(--font-cormorant)", fontSize: "18px", fontWeight: 600, color: "var(--ink)", marginBottom: 8 }}>2. Recommendation Disclaimer</h2>
          <p style={{ fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 8 }}>
            GoShed may provide suggestions, rankings, or recommendations generated by automated systems. These recommendations:
          </p>
          <ul style={{ fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 12, paddingLeft: 20 }}>
            <li>Are informational only</li>
            <li>Are not guarantees or professional advice</li>
            <li>May be incomplete, inaccurate, or outdated</li>
          </ul>
          <p style={{ fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 8 }}>
            You are solely responsible for any decisions you make based on GoShed&apos;s recommendations.
          </p>
          <p style={{ fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 0 }}>
            GoShed is not responsible for purchases, financial decisions, or other actions taken by users.
          </p>
        </section>

        <section style={{ marginBottom: 24 }}>
          <h2 style={{ fontFamily: "var(--font-cormorant)", fontSize: "18px", fontWeight: 600, color: "var(--ink)", marginBottom: 8 }}>3. User Responsibility</h2>
          <p style={{ fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 8 }}>By using GoShed you agree that:</p>
          <ul style={{ fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 0, paddingLeft: 20 }}>
            <li>You will use the service for lawful purposes only</li>
            <li>You will not attempt to disrupt or misuse the platform</li>
            <li>You understand that recommendations are suggestions, not instructions</li>
          </ul>
        </section>

        <section style={{ marginBottom: 24 }}>
          <h2 style={{ fontFamily: "var(--font-cormorant)", fontSize: "18px", fontWeight: 600, color: "var(--ink)", marginBottom: 8 }}>4. Third-Party Products or Services</h2>
          <p style={{ fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 0 }}>
            GoShed may reference products, services, or businesses. These are not endorsements, and GoShed is not responsible for third-party products, transactions, or experiences.
          </p>
        </section>

        <section style={{ marginBottom: 24 }}>
          <h2 style={{ fontFamily: "var(--font-cormorant)", fontSize: "18px", fontWeight: 600, color: "var(--ink)", marginBottom: 8 }}>5. Limitation of Liability</h2>
          <p style={{ fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 8 }}>
            To the fullest extent permitted by law, GoShed and its operators shall not be liable for:
          </p>
          <ul style={{ fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 0, paddingLeft: 20 }}>
            <li>Decisions made based on recommendations</li>
            <li>Purchases or financial outcomes</li>
            <li>Errors, interruptions, or inaccuracies in the service</li>
          </ul>
        </section>

        <section style={{ marginBottom: 24 }}>
          <h2 style={{ fontFamily: "var(--font-cormorant)", fontSize: "18px", fontWeight: 600, color: "var(--ink)", marginBottom: 8 }}>6. Service Changes</h2>
          <p style={{ fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 0 }}>
            We may update, modify, or discontinue parts of the service at any time as we continue improving GoShed.
          </p>
        </section>

        <section style={{ marginBottom: 0 }}>
          <h2 style={{ fontFamily: "var(--font-cormorant)", fontSize: "18px", fontWeight: 600, color: "var(--ink)", marginBottom: 8 }}>7. Contact</h2>
          <p style={{ fontSize: 14, lineHeight: 1.6, color: "var(--ink)", marginBottom: 0 }}>
            Questions about these terms can be sent to:{" "}
            <a href="mailto:support@thriftshopper.com" style={{ color: "var(--accent)", textDecoration: "none" }}>support@thriftshopper.com</a>
          </p>
        </section>
      </div>
    </main>
  );
}
